steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/virtual-agent:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/virtual-agent:$SHORT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'virtual-agent'
      - '--image=gcr.io/$PROJECT_ID/virtual-agent:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--port=8080'
      - '--quiet'
images:
  - 'gcr.io/$PROJECT_ID/virtual-agent:$SHORT_SHA'
